stations_ny = [
    "Times Square",
    "34th Street",
    "28th Street",
    "23rd Street",
    "Union Square",
    "8th Street",
    "Prince Street",
    "Canal Street",
    "Fulton Street",
    "Wall Street",
    "Clark Street",
    "Borough Hall",
    "Nevins Street",
    "Atlantic Avenue",
]

connections_ny = [
    ("Times Square", "34th Street"),
    ("34th Street", "28th Street"),
    ("28th Street", "23rd Street"),
    ("23rd Street", "Union Square"),
    ("Union Square", "8th Street"),
    ("8th Street", "Prince Street"),
    ("Prince Street", "Canal Street"),
    ("Canal Street", "Fulton Street"),
    ("Fulton Street", "Wall Street"),
    ("Clark Street", "Borough Hall"),
    ("Borough Hall", "Nevins Street"),
    ("Nevins Street", "Atlantic Avenue"),
    ("Times Square", "Union Square"),
    ("Union Square", "Canal Street"),
    ("Canal Street", "Wall Street"),
    ("Wall Street", "Clark Street"),
]

weighted_edges = [
    ("Times Square", "34th Street", 2),
    ("34th Street", "28th Street", 1),
    ("28th Street", "23rd Street", 1),
    ("23rd Street", "Union Square", 1),
    ("Union Square", "8th Street", 1),
    ("8th Street", "Prince Street", 1),
    ("Prince Street", "Canal Street", 1),
    ("Canal Street", "Fulton Street", 2),
    ("Fulton Street", "Wall Street", 2),
    ("Clark Street", "Borough Hall", 1),
    ("Borough Hall", "Nevins Street", 1),
    ("Nevins Street", "Atlantic Avenue", 1),
    ("Times Square", "Union Square", 5),
    ("Union Square", "Canal Street", 2),
    ("Canal Street", "Wall Street", 2),
    ("Wall Street", "Clark Street", 3),
]
